# Generated by Django 4.0.3 on 2022-03-28 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_alter_ngo_about_us_alter_ngo_address_alter_ngo_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_verify',
            field=models.BooleanField(default=False),
        ),
    ]
