# Generated by Django 4.0.3 on 2022-03-28 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_alter_user_is_verify'),
    ]

    operations = [
        migrations.AddField(
            model_name='ngo',
            name='logo',
            field=models.FileField(default='ngo_default.png', upload_to='media/images/'),
        ),
    ]
