# Generated by Django 4.0.3 on 2022-03-31 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0007_alter_ngo_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ngo',
            name='email',
        ),
    ]
