# Generated by Django 4.0.3 on 2022-04-05 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0010_foodpickup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodpickup',
            name='pick_up_address',
            field=models.TextField(default=''),
        ),
    ]
